### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by jbaumgartl** [hse-digital-engineering/build-your-own-chatbot-clean#1]
### Repo in der Studenten Org anlegen
- [ ] Clone von dem cleanen Build your own chatbot repo erstellen

> Die Verwendung eines Branching Models und github Issues ist zwingend erforderlich

- [ ] Issue1 für die erste Aufgabenstellung erstellen
- [ ] Weitere Issues erstellen
- [ ] Branch für den Issue1 erstellen
- [ ] Erste Aufgabenstellung bearbeiten

### Aufgabenstellung als Issue Anlegen in den Repos anlegen Labor Technische Informatik - Canvas

Issue 1

- [ ] Canvas ausfüllen und vorstellen
- [ ] Felder für Architecture Decision Records identifizieren
- [ ] Erste Vorstellung des Canvas in der Klasse und check, ob die eigenen Features umsetzbar sind
 
Issue 2

- [ ] Use Case Diagram in excalidraw erstellen und markdown einfügen
- [ ] Konkrete quality goals nach Vorlage formulieren
- [ ] Anforderungen der eigenen features formulieren
- [ ] ADRs für die eigenen Anforderungen und Qualitiy Goal identifizieren und anfertigen
